# Fast configuration for quick testing
# This config uses minimal parameters to test if all components work
# Estimated time: ~30 minutes total (vs 5-30 hours for full configs)

# System parameters
N: 5
N_global: 6  # N + 1 for CUDA kernel

# Dataset generation (reduced for speed)
dataset:
  samples_per_type: 1000   # Reduced from 37500 (total = 2000 samples)
  train_size: 1800         # Reduced from 70000
  K_max: 5120              # Reduced from 20480 (fewer Monte Carlo samples)
  save_json: false

# Training parameters (reduced for speed)
training:
  model_name: "fast_test"
  epochs: 50               # Reduced from 400
  constrain_weight: 0.0001
  batch_size: 128
  learning_rate: 0.001

# Experiment parameters (minimal testing)
experiment:
  num_simulations: 2       # Reduced from 10
  update_count: 5          # Reduced from 10
  it_idx: 5                # Reduced from 10
  K_max: 5120              # Reduced from 20480
  methods:
    - "iMP"                # Keep best method
    - "MP"                 # Keep fast method
    # - "ODE"              # Skip - very slow!
    - "ENTROPY"            # Keep for comparison
    - "RANDOM"             # Keep baseline

# Paths (relative to project root)
paths:
  data_dir: "data"
  models_dir: "models"
  results_dir: "results"

